name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Build Cypress image
        run: docker build -t cypress-image .

      - name: Run Cypress tests and generate reports
        run: bash run_tests.sh

      - name: Publish Test Results Json
        uses: phoenix-actions/test-reporting@v8
        if: always()
        with:
          name: Mochaawesome reporter
          path: cypress/reports/mocha/*.json
          reporter: mochawesome-json

      - name: Publish Test Results Html
        uses: actions/upload-artifact@v2
        with: 
          name: Html report
          path: cypress/reports/report.html