name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Cypress image
        run: docker build -t cypress-image .

      - name: Run Cypress tests
        run: bash run_tests.sh

      - name: Combine reports into Json
        run: npm run combine-reports

      - name: Generate Html report
        run: npm run generate-report
        
      - name: Publish Test Results Json
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files:
            cypress/reports/report.json

      - name: Publish Test Results Html
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: cypress/reports/report.html