name: Pull Request Workflow - Cypress Tests
on:
  pull_request:
    branches:
      - master
      - main
      - 'feature/**'

jobs:
  cypress-smoke:
    name: Run smoke test
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .github/docker/docker-compose-smoke.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker-compose build

      - name: Run Cypress tests
        run: docker-compose up --exit-code-from cypress-smoke
  cypress-tests:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .github/docker/docker-compose-tests.yml

    services:
      cypress-pdp:
        image: cypress-image
        build:
          context: ../../
          dockerfile: .github/docker/Dockerfile.tests
        container_name: cypress-pdp
        command: npx cypress run --spec "cypress/e2e/pdp*.cy.js"

      cypress-plp:
        image: cypress-image
        build:
          context: ../../
          dockerfile: .github/docker/Dockerfile.tests
        container_name: cypress-plp
        command: npx cypress run --spec "cypress/e2e/plp*.cy.js"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker-compose build

      - name: Run Cypress tests
        run: docker-compose up --exit-code-from cypress-tests